config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

app/models/fields/core_field.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
#
# Table name: fields
#
#  id             :integer         not null, primary key
#  type           :string(255)
#  field_group_id :integer
#  position       :integer
#  name           :string(64)
#  label          :string(128)
#  hint           :string(255)
#  placeholder    :string(255)
#  as             :string(32)
#  collection     :text
#  disabled       :boolean
#  required       :boolean
#  maxlength      :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class CoreField < Field
  # Some CoreField attributes should be read-only
  attr_readonly :name, :as, :collection
  before_destroy :error_on_destroy

  def error_on_destroy
    errors.add_to_base "Core fields cannot be deleted."
  end
end

app/models/fields/custom_field.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
#
# Table name: fields
#
#  id             :integer         not null, primary key
#  type           :string(255)
#  field_group_id :integer
#  position       :integer
#  name           :string(64)
#  label          :string(128)
#  hint           :string(255)
#  placeholder    :string(255)
#  as             :string(32)
#  collection     :text
#  disabled       :boolean
#  required       :boolean
#  maxlength      :integer
#  created_at     :datetime
#  updated_at     :datetime
#

# Implementation Notes
#------------------------------------------------------------------------------
# Adding database columns dynamically is not usually recommended,
# and can be potentially unsafe. However, the only alternative would be static migrations,
# and we want to let users add custom fields without having to restart their server.
# We could not use the EAV model for performance reasons, since we need to retain the
# ability to filter and search across thousands of records with potentially hundreds
# of custom fields.
#
# We have solved all of the major issues:
#
# * Custom fields for view templates are dynamically generated based on normalized
#   database records in the 'fields' table, instead of ActiveRecord's cached attributes.
# * Concurrency issues are resolved by using 'method_missing' to refresh a model's column information
#   when fields are added by a separate server process.
# * The custom field can be renamed or deleted, but database columns are never renamed or destroyed.
#   A rake task can be run to purge any orphaned columns.
# * Custom field types can only be changed if the database can support the transition.
#   For example, you can change an 'email' field to a 'string', but not to a 'datetime',
#   since changing the type of the database column would cause data to be lost.
#

class CustomField < Field
  after_validation :update_column, :on => :update
  before_create    :add_column

  SAFE_DB_TRANSITIONS = {
    :any => [[:date, :time, :timestamp], [:integer, :float]],
    :one => {:string => :text}
  }

  def available_as
    Field.field_types.reject do |new_type, params|
      db_transition_safety(as, new_type) == :unsafe
    end
  end

protected

  # When changing a custom field's type, it may be necessary to
  # change the column type in the database. This method returns
  # the safety of a given transition.
  # Returns:
  #   :null   => no transition needed
  #   :safe   => transition is safe
  #   :unsafe => transition is unsafe
  def db_transition_safety(old_type, new_type = self.as)
    old_col, new_col = [old_type, new_type].map{|t| column_type(t) }
    return :null if old_col == new_col  # no transition needed
    return :safe if SAFE_DB_TRANSITIONS[:one].any? do |start, final|
      old_col == start && new_col == final  # one-to-one
    end
    return :safe if SAFE_DB_TRANSITIONS[:any].any? do |col_set|
      [old_col, new_col].all?{|c| col_set.include?(c)}  # any-to-any
    end
    :unsafe # Else, unsafe.
  end

  def table_name
    klass.table_name
  end

  def klass_column_names
    klass.columns.map(&:name)
  end

  def generate_column_name
    # Generate column name for custom field.
    # If column name is already taken, a numeric suffix is appended.
    # Example column sequence: cf_custom, cf_custom_2, cf_custom_3, ...
    suffix = nil
    field_name = 'cf_' + label.downcase.gsub(/[^a-z0-9]+/, '_')
    while (final_name = [field_name, suffix].compact.join('_')) &&
          klass_column_names.include?(final_name) do
      suffix = (suffix || 1) + 1
    end
    final_name
  end

  # Returns options for ActiveRecord operations
  def column_options
    Field.field_types[self.as][:options] || {}
  end

  def add_column
    self.name = generate_column_name if name.blank?
    connection.add_column(table_name, name, column_type, column_options)
    klass.reset_column_information
  end

  def update_column
    # Change database column type if appropriate
    # (NOTE: Columns will never be renamed or destroyed)
    if self.errors.empty? && db_transition_safety(as_was) == :safe
      connection.change_column(table_name, name, column_type, column_options)
      klass.reset_column_information
    end
  end
end

app/controllers/admin/fields_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Admin::FieldsController < Admin::ApplicationController
  before_filter "set_current_tab('admin/fields')", :only => [ :index ]

  load_resource

  # GET /fields
  # GET /fields.xml                                                      HTML
  #----------------------------------------------------------------------------
  def index
  end

  # GET /fields/1
  # GET /fields/1.xml                                                    HTML
  #----------------------------------------------------------------------------
  def show
    respond_with(@field)
  end

  # GET /fields/new
  # GET /fields/new.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def new
    @field = CustomField.new(:field_group_id => params[:field_group_id])

    respond_with(@custom_field)
  end

  # GET /fields/1/edit                                                   AJAX
  #----------------------------------------------------------------------------
  def edit
    @field = Field.find(params[:id])

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = Field.find_by_id($1) || $1.to_i
    end

    respond_with(@field)
  end

  # POST /fields
  # POST /fields.xml                                                     AJAX
  #----------------------------------------------------------------------------
  def create
    @field = CustomField.create(params[:field])

    respond_with(@field)
  end

  # PUT /fields/1
  # PUT /fields/1.xml                                                    AJAX
  #----------------------------------------------------------------------------
  def update
    @field = Field.find(params[:id])
    @field.update_attributes(params[:field])

    respond_with(@field)
  end

  # DELETE /fields/1
  # DELETE /fields/1.xml                                        HTML and AJAX
  #----------------------------------------------------------------------------
  def destroy
    @field = CustomField.find(params[:id])
    @field.destroy

    respond_with(@field)
  end

  # POST /fields/sort
  #----------------------------------------------------------------------------
  def sort
    field_group_id = params[:field_group_id].to_i
    field_ids = params["fields_field_group_#{field_group_id}"] || []

    field_ids.each_with_index do |id, index|
      Field.update_all({:position => index+1, :field_group_id => field_group_id}, {:id => id})
    end

    render :nothing => true
  end

  # POST /fields/auto_complete/query                                     AJAX
  #----------------------------------------------------------------------------
  # Handled by before_filter :auto_complete, :only => :auto_complete
end

app/helpers/admin/fields_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module Admin::FieldsHelper

  # Returns the list of :null and :safe database column transitions.
  # Only these options should be shown on the custom field edit form.
  def field_edit_as_options(field)
    # Return every available field_type if no restriction
    options = field.as.blank? ? Field.field_types.keys : field.available_as.keys
    options.map{|k| [t("field_types.#{k}"), k] }
  end

  def field_group_options
    FieldGroup.all.map {|fg| [fg.name, fg.id]}
  end
end

app/helpers/fields_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module FieldsHelper
end

app/views/admin/fields/_edit.html.haml
.remote
  = form_for([:admin, @field], :as => :field, :html => one_submit_only(:field).merge(:class => "edit_field", :id => "edit_field_#{@field.id}"), :remote => true) do |f|
    = link_to_close edit_admin_field_path(@field)
    = f.error_messages
    = render :partial => "top_section", :locals => { :f => f, :edit => true }
    .buttonbar
      = f.submit t(:save_field), :id => :field_submit
      or
      = link_to_cancel edit_admin_field_path(@field)

app/views/admin/fields/_field.html.haml
%li.highlight.position[field]
  %span.handle
    %img( src="/assets/sortable.gif" )

  .tools
    %small
      = link_to_edit(field, :url => edit_admin_field_path(field), :klass_name => 'Field') + " | "
      = link_to_delete(field, :url => admin_field_path(field), :klass_name => 'Field')

  %tt
    %b= field.label
    == (#{t('field_types.' + field.as)})

    == added #{time_ago_in_words(field.created_at)} ago
    = hook(:field_bottom, self, :field => field)

app/views/admin/fields/_new.html.haml
- path = new_admin_field_path(:field_group_id => @field.field_group_id)

= form_for([:admin, @field], :as => :field, :html => one_submit_only(:field), :remote => true) do |f|
  = link_to_close path
  = f.error_messages
  = render :partial => "top_section", :locals => { :f => f }
  .buttonbar
    = f.submit t(:create_field), :id => :field_submit
    or
    = link_to_cancel path

app/views/admin/fields/_options.html.haml
%p
  = link_to_close options_admin_fields_path
  = hidden_field_tag "field[user_id]", @current_user.id
  == Sort Custom fields by #{link_to(@sort_by, "#", :id => :sort_by)}.
  == Show #{link_to(@per_page, "#", :id => :per_page)} field records per page
  == using #{link_to(@outline, "#", :id => :outline)} format.
%p

%script
  = render :partial => "sort_by"
  = render :partial => "shared/per_page"
  = render :partial => "shared/outline"

app/views/admin/fields/_sort_by.html.haml
- sort_by_menu_items = ["Field name", "Field label", "Field type", "Table name", "Display sequence", "Display block", "Display width", "Max size"].inject([]) do | items, sort_by|
  - items << %Q[{ name: "#{sort_by}", on_select: function() { #{redraw(:sort_by, sort_by.downcase!)} } }]

:plain
  new crm.Menu({
    trigger   : "sort_by",
    fade      : 0.5,
    appear    : 0.5,
    menu_items: [ #{sort_by_menu_items.join(",")} ]
  });

app/views/admin/fields/_top_section.html.haml
.section
  = f.hidden_field :field_group_id

  %table
    %tr
      %td
        .label.top.req Field label:
        = f.text_field :label, :id => :field_label

      - if f.object.is_a? CustomField
        %td= spacer
        %td
          .label.top.req Field type:
          = f.select :as, field_edit_as_options(f.object)
    %tr
      %td
        .label.top.req Select Options (pipe separated):
        = f.text_field :collection_string
    %tr
      %td
        .label.top Required:
        = f.check_box :required
      %td= spacer
      %td
        .label.top Disabled:
        = f.check_box :disabled
    %tr
      %td
        .label.top Hint:
        = f.text_area :hint, :rows => 5
      %td= spacer
      %td
        .label.top Placeholder:
        = f.text_area :placeholder, :rows => 5

    = hook(:customfield_top_section_bottom, self, :f => f)

    :javascript
      var toggleCollection = function(){
        var select_el = $('field_collection_string');
        switch($('field_as').value){
          case "select":
          case "multiselect":
          case "check_boxes":
            select_el.show().previous().show().innerHTML = "Select Options (pipe separated):";
            break;
          default:
            select_el.hide().previous().hide();
        }
      };

      toggleCollection();

      Event.observe($('field_as'), 'change', toggleCollection);

app/views/admin/fields/index.html.haml
= styles_for :fields

.title
  %span#create_field_title= t(:admin_tab_fields)

.info= t(:admin_fields_info).html_safe

.inline_tabs
  %ul
    - Field::KLASSES.each do |klass|
      %li{ "data-tab-class" => klass.name.downcase, :class => ("selected" if klass == Contact) }
        = link_to t(klass.name.downcase), "#"

- Field::KLASSES.each do |klass|
  - asset = klass.name.downcase
  .fields{ :id => "#{asset}_section", :style => ("display: none;" if klass != Contact) }

    - create_form_id = "#{asset}_create_field_group"

    .title_tools
      = link_to_inline(create_form_id, new_admin_field_group_path(:klass_name => klass.name), :text => t(:create_field_group))

    .title
      = t(asset)

    .remote{ hidden.merge(:id => create_form_id) }

    - container_id = "#{asset}_field_groups"
    .list{ :id => container_id }
      = render :partial => "admin/field_groups/field_group", :collection => klass.field_groups, :locals => {:asset => asset, :klass => klass}

    - group_list_ids = klass.field_groups.map {|field_group| dom_id(field_group, :fields)}
    - klass.field_groups.each do |field_group|
      = sortable_element(dom_id(field_group, :fields), :url => sort_admin_fields_path(:field_group_id => field_group.id), :containment => group_list_ids, :dropOnEmpty => true)

    = sortable_element(container_id, :url => sort_admin_field_groups_path(:asset => asset), :tag => :div)

app/views/admin/fields/show.html.haml
= styles_for :field

#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_field, edit_admin_field_path(@field), :text => "Edit") + " | "
.title#edit_field_title= @field.field_label

%div#edit_field{ hidden }

%tt
  %br
  Label:
  %b
    - if @field.field_label?
      = @field.field_label
  %br
  Name:
  %b
    - if @field.field_name?
      = @field.field_name
  %br
  Table:
  %b
    - if @field.table_name?
      = @field.table_name.pluralize
  %br
  Type:
  %b
    - if @field.field_type?
      = @field.field_type
  %br
  %br
  Created at:
  %b
    = @field.created_at.to_s
  %br
  Updated at:
  %b
    = @field.updated_at.to_s

= hook(:show_field_bottom, self)