config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
    end
  end

  namespace :admin do
    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

app/models/users/ability.rb
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      entities = [Account, Campaign, Contact, Lead, Opportunity]

      can :create, :all
      can :manage, entities, :access => 'Public'
      can :manage, entities + [Task], :user_id => user.id

      entities.each do |klass|
        permissions = user.permissions.where(:asset_type => klass.name)
        can :manage, klass, :id => permissions.map(&:asset_id)
      end
    end
  end
end

app/models/users/authentication.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Authentication < Authlogic::Session::Base # NOTE: This is not ActiveRecord model.
  authenticate_with User
  after_save :check_if_suspended

  def to_key
    id ? id : nil
  end

  private

  # Override Authlogic's validate_by_password() to allow blank passwords. See
  # authlogic/lib/authlogic/session/password.rb for details.
  #----------------------------------------------------------------------------
  def validate_by_password
    self.invalid_password = false

    self.attempted_record = search_for_record(find_by_login_method, send(login_field))
    if attempted_record.blank?
      generalize_credentials_error_messages? ?
        add_general_credentials_error :
        errors.add(login_field, I18n.t('error_messages.login_not_found', :default => "is not valid"))
      return
    end

    if !attempted_record.send(verify_password_method, send("protected_#{password_field}"))
      self.invalid_password = true
      generalize_credentials_error_messages? ?
        add_general_credentials_error :
        errors.add(password_field, I18n.t('error_messages.password_invalid', :default => "is not valid"))
      return
    end
  end

  # Override Authologic instance method in order to keep :login_count,
  # :last_login_at, and :last_login_ip intact if the user is suspended.
  # See vendor/plugin/authlogin/lib/authlogic/session/magic_columns.rb.
  #----------------------------------------------------------------------------
  def update_info
    super unless self.user.suspended?
  end

  #----------------------------------------------------------------------------
  def check_if_suspended
    self.errors.add(:base, I18n.t(:msg_account_suspended)) if self.user.suspended?
  end
end

app/models/users/permission.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
#
# Table name: permissions
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  asset_id   :integer
#  asset_type :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :asset, :polymorphic => true

  validates_presence_of :user_id
end

app/controllers/admin/users_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Admin::UsersController < Admin::ApplicationController
  before_filter "set_current_tab('admin/users')", :only => [ :index, :show ]

  load_resource :except => [:create]

  # GET /admin/users
  # GET /admin/users.xml                                                   HTML
  #----------------------------------------------------------------------------
  def index
    @users = get_users(:page => params[:page])
    respond_with(@users)
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  #----------------------------------------------------------------------------
  def show
    respond_with(@user)
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml                                               AJAX
  #----------------------------------------------------------------------------
  def new
    respond_with(@user)
  end

  # GET /admin/users/1/edit                                                AJAX
  #----------------------------------------------------------------------------
  def edit
    if params[:previous].to_s =~ /(\d+)\z/
      @previous = User.find_by_id($1) || $1.to_i
    end

    respond_with(@user)
  end

  # POST /admin/users
  # POST /admin/users.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def create
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    admin = params[:user].delete(:admin)
    @user = User.new(params[:user])
    @user.admin = (admin == "1")
    @user.save_without_session_maintenance
    @users = get_users

    respond_with(@user)
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml                                                 AJAX
  #----------------------------------------------------------------------------
  def update
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    admin = params[:user].delete(:admin)
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    @user.admin = (admin == "1")
    @user.save_without_session_maintenance

    respond_with(@user)
  end

  # GET /admin/users/1/confirm                                             AJAX
  #----------------------------------------------------------------------------
  def confirm
    respond_with(@user)
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml                                              AJAX
  #----------------------------------------------------------------------------
  def destroy
    unless @user.destroy
      flash[:warning] = t(:msg_cant_delete_user, @user.full_name)
    end

    respond_with(@user)
  end

  # POST /users/auto_complete/query                                        AJAX
  #----------------------------------------------------------------------------
  # Handled by Admin::ApplicationController :auto_complete

  # PUT /admin/users/1/suspend
  # PUT /admin/users/1/suspend.xml                                         AJAX
  #----------------------------------------------------------------------------
  def suspend
    @user.update_attribute(:suspended_at, Time.now) if @user != @current_user

    respond_with(@user)
  end

  # PUT /admin/users/1/reactivate
  # PUT /admin/users/1/reactivate.xml                                      AJAX
  #----------------------------------------------------------------------------
  def reactivate
    @user.update_attribute(:suspended_at, nil)

    respond_with(@user)
  end

private

  #----------------------------------------------------------------------------
  def get_users(options = {})
    self.current_page  = options[:page] if options[:page]
    self.current_query = params[:query] if params[:query]

    @search = klass.search(params[:q])
    @search.build_grouping unless @search.groupings.any?

    wants = request.format
    scope = User.by_id
    scope = scope.merge(@search.result)
    scope = scope.text_search(current_query)      if current_query.present?
    scope = scope.paginate(:page => current_page) if wants.html? || wants.js? || wants.xml?
    scope
  end
end

app/helpers/admin/users_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module Admin::UsersHelper

  def link_to_suspend(user)
    link_to(t(:suspend) + "!", suspend_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_reactivate(user)
    name = user.awaits_approval? ? t(:approve) + "!" : t(:reactivate) + "!"
    link_to(name, reactivate_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_confirm(user)
    link_to(t(:delete) + "?", confirm_admin_user_path(user), :method => :get, :remote => true)
  end

  # User summary info for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def user_summary(user)
    summary = []
    title_and_company = user.title.blank? ? '' : h(user.title)
    title_and_company << " #{t(:at)} #{user.company}" unless user.company.blank?
    summary << title_and_company unless title_and_company.blank?
    summary << t('pluralize.login', user.login_count) if user.last_request_at && user.login_count > 0
    summary << user.email
    summary << "#{t :phone_small}: #{user.phone}" unless user.phone.blank?
    summary << "#{t :mobile_small}: #{user.mobile}" unless user.mobile.blank?
    summary << if !user.suspended?
      t(:user_since, l(user.created_at.to_date, :format => :mmddyy))
    elsif user.awaits_approval?
      t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))
    else
      t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))
    end
    summary << if user.awaits_approval?
      t(:user_signed_up)
    elsif user.suspended?
      t(:user_suspended)
    elsif user.admin?
      t(:user_admin)
    else
      t(:user_active)
    end
    summary.join(', ')
  end
end

app/helpers/users_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module UsersHelper

  def language_for(user)
    if user.preference[:locale]
      locale, language = languages.detect{ |locale, language| locale == user.preference[:locale] }
    end
    language || "English"
  end

  def sort_by_language
    languages.sort.map do |locale, language|
      %Q[{ name: "#{language}", on_select: function() { #{redraw(:locale, [ locale, language ], url_for(:action => :redraw))} } }]
    end
  end
  
  def user_select(asset)
    collection_select asset, :assigned_to, @users, :id, :full_name,
                      { :include_blank => "" }, 
                      { :"data-placeholder" => t(:myself),
                        :style => "width:160px" } 
  end
end

app/views/admin/users/_confirm.html.haml
.confirm[@user, :confirm]
  #{t :user_confirm_delete}
  #{t :delete} <b>#{@user.full_name}</b>?
  = link_to_confirm_delete(@user) << " : "
  = link_to_function(t(:no_button), "crm.flick('#{dom_id(@user, :confirm)}', 'remove')")

app/views/admin/users/_edit.html.haml
.remote
  = form_for([:admin, @user], :html => one_submit_only(:user).merge({:autocomplete => 'off'}), :remote => true) do |f|
    = link_to_close edit_admin_user_path(@user)

    = f.error_messages :object_name => t('user')

    = render "admin/users/profile", :f => f, :edit => true
    .buttonbar
      = f.submit t(:save_user)
      #{t :or}
      = link_to_cancel edit_admin_user_path(@user)

app/views/admin/users/_new.html.haml
= form_for([:admin, @user], :html => one_submit_only(:user).merge({:autocomplete => 'off'}), :remote => true) do |f|
  = link_to_close new_admin_user_path

  = f.error_messages :object_name => t('user')

  = render "admin/users/profile", :f => f
  .buttonbar
    = f.submit t(:create_user)
    #{t :or}
    = link_to_cancel new_admin_user_path

app/views/admin/users/_profile.html.haml
- edit ||= false
.section
  %table
    %tr
      %td
        .label.top.req #{t :username}:
        = f.text_field :username
      %td= spacer
      %td
        .label.top.req #{t :email}:
        = f.text_field :email
    %tr
      %td
        .label #{t :password}:
        = f.password_field :password
      %td= spacer
      %td
        .label #{t :password_confirmation}:
        = f.password_field :password_confirmation
    %tr
      %td(colspan=3)
        .check_box(style="margin-top:6px")
          -# Sorry, you can't revoke Admin rights from yourself.
          = f.check_box(:admin, { :disabled => edit && @user == @current_user })
          %label{:for => 'user_admin'}
            = t(:user_is_admin)
.subtitle #{t :personal_information}
.section
  %table
    %tr
      %td
        .label #{t :first_name}:
        = f.text_field :first_name
      %td= spacer
      %td
        .label #{t :last_name}:
        = f.text_field :last_name
    %tr
      %td
        .label #{t :job_title}:
        = f.text_field :title
      %td= spacer
      %td
        .label #{t :company}:
        = f.text_field :company

app/views/admin/users/_sidebar_index.html.haml
.filters#filters
  = render "shared/search"

app/views/admin/users/_user.html.haml
%li.highlight[user]

  - if user.awaits_approval?
    .strip.signed_up #{t :user_signed_up}
  - elsif user.suspended?
    .strip.suspended #{t :user_suspended}
  - elsif user.admin?
    .strip.admin #{t :user_admin}
  - else
    .strip.active #{t :user_active}

  = avatar_for(user, :size => :medium, :width => 30, :height => 30 )

  .indentfull
    .tools
      = link_to_edit(user, :url => edit_admin_user_path(user)) << " | "

      - if user.suspended?
        = link_to_reactivate(user) << " | "
      - elsif user != @current_user
        = link_to_suspend(user) << " | "
      - else
        = "<font color='silver'>#{t :suspend}!</font> | ".html_safe

      - if user != @current_user
        = link_to_confirm(user)
      - else
        %span.grayed #{t :delete}?

    %span.black #{link_to(h(user.full_name), user)} (#{user.username})
    %tt
      = "- #{h(user.title)}" unless user.title.blank?
      = " " + t(:at) + " " + h(user.company) unless user.company.blank?

      %span.black= "|"
      - if user.last_request_at && user.login_count > 0
        = t('pluralize.login', user.login_count)
        %span.black= "|"

      - if user.awaits_approval?
        %b.cool #{t :user_awaits_approval}
      - elsif user.last_request_at
        %span.cool #{t(:last_seen, time_ago_in_words(user.last_request_at))}
      - else
        %span.warn #{t :user_never_logged_in}
    %dt{ :style => "padding: 2px 0px 0px 0px" }
      = link_to_email(user.email.to_s) << " | "
      = "#{t :phone_small}: <b>".html_safe + user.phone << "</b> | ".html_safe if user.phone?
      = "#{t :mobile_small}: <b>".html_safe + user.mobile << "</b> | ".html_safe if user.mobile?

      - if !user.suspended?
        %span #{t(:user_since, l(user.created_at.to_date, :format => :mmddyy))}
      - elsif user.awaits_approval?
        %b.cool #{t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))}
      - else
        %span.warn #{t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))}

app/views/admin/users/index.html.haml
= styles_for :user

.title_tools
  = link_to_inline(:create_user, new_admin_user_path, :text => t(:create_user))

.title
  %span#create_user_title #{t :users}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#create_user{ hidden }

.list#users= render :partial => "admin/users/user", :collection => @users
#paginate= render "shared/paginate"
#export= render "shared/export"

app/views/admin/users/show.html.haml
.title= h(@user.full_name)
%p
:erb
  <%= link_to t(:edit), edit_admin_user_path(@user) %> |
  <%= link_to t(:back), admin_users_path %>